name: CI/CD Pipeline

on:
  push:
    branches:
      - staging
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' 
      
      - name: Install dependencies
        run: |
          echo "------Installing Dependencies------"
          pip install --upgrade pip
          pip install flask pytest
          echo "------Completed Installing Dependencies-------"

      - name: Run tests
        run: |
          echo "-------Running Test Script-------"
          pytest --disable-warnings -q

      - name: Build Application
        run: |
          echo "-------Building application-------"

      - name: SSH into EC2 and Prepare Target Directory
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo apt-get update
            sudo apt update
            sudo apt install python
            curl -sS https://bootstrap.pypa.io/get-pip.py | python
            pip3 install flask pytest
      - name: Copy code to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: ./
          target: ./
          script: |
            sudo python3 ./JenkinsPipeline/Calculator_flask/app.py

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' 
      
      - name: Install dependencies
        run: |
          echo "------Installing Dependencies------"
          pip install --upgrade pip
          pip install flask pytest
          echo "------Completed Installing Dependencies-------"

      - name: Run tests
        run: |
          echo "-------Running Test Script-------"
          pytest --disable-warnings -q

      - name: Build Application
        run: |
          echo "------Building application------"
      
      - name: Deploy to Production
        run: |
          echo "--------Deploying to Production-------"
          
