name: CI/CD Pipeline

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' 
      
      - name: Install dependencies
        run: |
          echo "------Installing Dependencies------"
          pip install --upgrade pip
          pip install flask pytest
          echo "------Completed Installing Dependencies-------"

      - name: Run tests
        run: |
          echo "-------Running Test Script-------"
          pytest --disable-warnings -q

      - name: Build Application
        run: |
          echo "Building application..."

  generate_tag:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check Tag
        run: |
          CURRENT_TAG = "git tag --sort=-v:refname | head -n 1"
          echo "Current tag is: $CURRENT_TAG"
          