name: CI/CD Pipeline

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' 
      
      - name: Install dependencies
        run: |
          echo "------Installing Dependencies------"
          pip install --upgrade pip
          pip install flask pytest
          echo "------Completed Installing Dependencies-------"

      - name: Run tests
        run: |
          echo "-------Running Test Script-------"
          pytest --disable-warnings -q

      - name: Build Application
        run: |
          echo "-------Building application-------"

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Check for Tag using GitHub Script
        id: check_tag
        uses: actions/github-script@v6
        with:
          script: |
            const tagName = 'v1.0.0';  // Replace with the tag you want to check
            try {
              const tag = await github.rest.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `tags/${tagName}`,
            });
            console.log(`Tag ${tagName} exists:`, tag.data);
            core.setOutput('tag_exists', 'true');
            } catch (error) {
            if (error.status === 404) {
              console.log(`Tag ${tagName} does not exist`);
              core.setOutput('tag_exists', 'false');
            } else {
              throw error;
            }
            }

      - name: SSH into EC2 and Installing Libraries
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo apt-get update
            sudo apt update
            sudo apt install python -y
            curl -sS https://bootstrap.pypa.io/get-pip.py | python3
            sudo apt install python3-pip -y
            sudo apt install nginx -y
            pip install flask pytest

      - name: Configuring Nginx and Running Calculator Application
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: ./
          target: ./
          script: |
            sudo rm -rf  /etc/nginx/sites-available/default
            sudo cp /home/ubuntu/default /etc/nginx/sites-available/
            sudo systemctl restart nginx
            cd /home/ubuntu/Calculator_flask/
            python3 -m flask run

      

          
